[http]
    [http.routers]
	[http.routers.dashboard]
	    entryPoints = ["web", "websecure"]
	    service = "dashboard"
	    middlewares = ["auth"]
	    rule = "Host(`dashboard.test.domain`)"
            [http.routers.dashboard.tls]
		certResolver = "cf-tls"

        [http.routers.auth]
            entryPoints = ["web", "websecure"]
            service = "auth"
            rule = "Host(`auth.test.domain`)"
            [http.routers.auth.tls]
                certResolver = "cf-tls"

    [http.middlewares]
	[http.middlewares.auth.forwardAuth]
	    address = "http://tinyauth:3000/api/auth/traefik"
    
    [http.services]
	[http.services.dashboard.loadBalancer]
	    [[http.services.dashboard.loadBalancer.servers]]
		url = "http://[your traefik ip]:8080"

	[http.services.auth.loadBalancer]
            [[http.services.auth.loadBalancer.servers]]
		url = "http://tinyauth:3000"

[tls.stores]
    [tls.stores.default.defaultGeneratedCert]
	resolver = "cf-tls"
	[tls.stores.default.defaultGeneratedCert.domain]
	    main = "test.domain"
	    sans = ["*.test.domain"]
