global:
  sendAnonymousUsage: false
  checkNewVersion: true

api:
  dashboard: true
  insecure: true
  debug: true

log:
  level: "DEBUG" #Change required After setup: INFO or ERROR
  filePath: "/etc/traefik/logs/log-file.log"

accessLog:
  filePath: "/etc/traefik/logs/access.log"
  filters:
    statusCodes:
      - "200-299"
      - "300-399"
      - "400-599"
    retryAttempts: true
    minDuration: "10ms"

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
          permanent: true

  websecure:
    address: ":443"
    http3:
      advertisedPort: 443

providers:
  file:
    watch: true
    filename: "/etc/traefik/dynamic.yml"

  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "traefik-network"
    watch: true

tls:
  certificates:
    - certFile: /etc/traefik/tls/cf-origin.pem
      keyFile: /etc/traefik/tls/cf-origin.key
  stores:
    default:
      defaultCertificate:
        certFile: "/etc/traefik/tls/cf-origin.pem"
        keyFile: "/etc/traefik/tls/cf-origin.key"