tunnel: your tunnel id
credentials-file: /etc/cloudflared/tunnel.json

ingress:
  - hostname: "*.your-domain.com"
    service: https://traefik:443
    originRequest:
      noTLSVerify: true

  - service: http_status:404